# Generated by Django 6.0.2 on 2026-02-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number', models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainProof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=255, unique=True)),
                ('stellar_transaction_hash', models.CharField(max_length=100, unique=True)),
                ('proof_hash', models.CharField(max_length=64)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='Rift_pay.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='Rift_pay.user')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rift_pay.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rift_pay.user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rift_pay.user'),
        ),
    ]
