# Generated by Django 6.0.2 on 2026-02-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rift_pay', '0007_mobilemoneytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTerminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('terminal_id', models.CharField(help_text='Unique terminal identifier', max_length=64, unique=True)),
                ('merchant_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('api_key_hash', models.CharField(help_text='Hashed API key for terminal authentication', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='systemactivity',
            name='action',
            field=models.CharField(choices=[('REGISTER', 'User registration'), ('LOGIN', 'User login'), ('LOGOUT', 'User logout'), ('TRANSFER', 'Money transfer'), ('DEPOSIT', 'Mobile money deposit'), ('WITHDRAW', 'Mobile money withdrawal'), ('MM_WEBHOOK', 'Mobile money webhook'), ('PROFILE_UPDATE', 'Profile update'), ('NFC_LINK', 'NFC card linked'), ('NFC_UNLINK', 'NFC card unlinked'), ('NFC_PAY', 'NFC payment')], max_length=20),
        ),
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_uid', models.CharField(help_text='Unique NFC chip identifier (UID)', max_length=32, unique=True)),
                ('label', models.CharField(blank=True, help_text="Friendly name, e.g. 'My blue card'", max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=50000, help_text='Maximum amount authorised per day (FCFA)', max_digits=10)),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, default=10000, help_text='Maximum amount per single tap (FCFA)', max_digits=10)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_cards', to='Rift_pay.account')),
                ('card', models.ForeignKey(blank=True, help_text="Optional link to the user's bank card", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='Rift_pay.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_cards', to='Rift_pay.user')),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='NFCPaymentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('DECLINED', 'Declined'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_payments', to='Rift_pay.account')),
                ('nfc_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Rift_pay.nfccard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_payments', to='Rift_pay.user')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='Rift_pay.nfcterminal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
