# Generated by Django 6.0.2 on 2026-02-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rift_pay', '0008_nfcterminal_alter_systemactivity_action_nfccard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_card', to='Rift_pay.user'),
        ),
    ]
