# Generated by Django 6.0.2 on 2026-02-18 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rift_pay', '0009_alter_nfccard_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfccard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='nfccard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Card creation date'),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='nfc_number',
            field=models.CharField(default='NFC 0000 0000 0000', help_text="System-generated card number (e.g. 'NFC 4821 7390 5612')", max_length=19, unique=True),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='ordered_at',
            field=models.DateTimeField(blank=True, help_text='When the user requested a physical card', null=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='card_uid',
            field=models.CharField(blank=True, help_text='Physical NFC chip UID – set by admin when linking the card', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='linked_at',
            field=models.DateTimeField(blank=True, help_text='When admin linked the physical UID', null=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='status',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('ORDERED', 'Ordered'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='VIRTUAL', max_length=10),
        ),
    ]
