# Generated by Django 6.0.2 on 2026-02-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rift_pay', '0010_alter_nfccard_options_nfccard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='nfc_number',
            field=models.CharField(help_text="System-generated card number (e.g. 'NFC 4821 7390 5612')", max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='systemactivity',
            name='action',
            field=models.CharField(choices=[('REGISTER', 'User registration'), ('LOGIN', 'User login'), ('LOGOUT', 'User logout'), ('TRANSFER', 'Money transfer'), ('DEPOSIT', 'Mobile money deposit'), ('WITHDRAW', 'Mobile money withdrawal'), ('MM_WEBHOOK', 'Mobile money webhook'), ('PROFILE_UPDATE', 'Profile update'), ('NFC_LINK', 'NFC card linked'), ('NFC_UNLINK', 'NFC card unlinked'), ('NFC_ORDER', 'NFC physical card ordered'), ('NFC_BLOCK', 'NFC card blocked'), ('NFC_PAY', 'NFC payment')], max_length=20),
        ),
    ]
