# Generated by Django 6.0.2 on 2026-02-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rift_pay', '0012_add_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_profile_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
