"""
Django settings for banking project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-w-a%gq*ocsx41*5g3xi^4msj*i%lnr@!p)xl-oczh+%!a)6)xo')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Rift_pay'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'banking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'banking' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'banking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Local fallback (used when DATABASE_URL is NOT set)
_LOCAL_DB = {
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': 'banking',
    'USER': 'postgres',
    'PASSWORD': 'Postgre218',
    'HOST': 'localhost',
    'PORT': '5432',
}

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres:Postgre218@localhost:5432/banking',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'banking' / 'static']  # Points to your project's static folder
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


BLOCKCHAIN_API_BASE_URL = os.getenv('BLOCKCHAIN_API_BASE_URL', 'http://localhost:8001')
BLOCKCHAIN_API_TRANSFER_PATH = os.getenv('BLOCKCHAIN_API_TRANSFER_PATH', '/api/transfers')
BLOCKCHAIN_API_TOKEN = os.getenv('BLOCKCHAIN_API_TOKEN', '')
BLOCKCHAIN_API_KEY = os.getenv('BLOCKCHAIN_API_KEY', 'dev-back-sec-key')
BLOCKCHAIN_API_KEY_HEADER = os.getenv('BLOCKCHAIN_API_KEY_HEADER', 'X-API-Key')
BLOCKCHAIN_API_TIMEOUT = int(os.getenv('BLOCKCHAIN_API_TIMEOUT', '15'))
BLOCKCHAIN_WEBHOOK_TOKEN = os.getenv('BLOCKCHAIN_WEBHOOK_TOKEN', 'dev-webhook-token')

MOBILE_MONEY_MODE = os.getenv('MOBILE_MONEY_MODE', 'manual')
MOBILE_MONEY_API_TIMEOUT = int(os.getenv('MOBILE_MONEY_API_TIMEOUT', '20'))
MOBILE_MONEY_WEBHOOK_TOKEN = os.getenv('MOBILE_MONEY_WEBHOOK_TOKEN', 'dev-mm-webhook-token')

ORANGE_MONEY_BASE_URL = os.getenv('ORANGE_MONEY_BASE_URL', '')
ORANGE_MONEY_TOKEN = os.getenv('ORANGE_MONEY_TOKEN', '')
ORANGE_MONEY_COLLECTION_PATH = os.getenv('ORANGE_MONEY_COLLECTION_PATH', '/api/collections')
ORANGE_MONEY_DISBURSEMENT_PATH = os.getenv('ORANGE_MONEY_DISBURSEMENT_PATH', '/api/disbursements')

MTN_MONEY_BASE_URL = os.getenv('MTN_MONEY_BASE_URL', '')
MTN_MONEY_TOKEN = os.getenv('MTN_MONEY_TOKEN', '')
MTN_MONEY_COLLECTION_PATH = os.getenv('MTN_MONEY_COLLECTION_PATH', '/api/collections')
MTN_MONEY_DISBURSEMENT_PATH = os.getenv('MTN_MONEY_DISBURSEMENT_PATH', '/api/disbursements')

# ─── Production security (only when DEBUG = False) ───
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ─── Email (SMTP) settings ───────────────────────────────────────────────────
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') or os.getenv('EMAIL_HOST_USER', 'noreply@riftpay.local')

# OTP validity duration in minutes
OTP_EXPIRY_MINUTES = int(os.getenv('OTP_EXPIRY_MINUTES', '10'))

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'